### ISSUE TITLE
Buttons are not clear

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-hungergames-react#2]
Why n, k and o in "No(n)", "Not sure (k)" and "Yes (o)"?

Is it related to keyboard actions? (Selecting n or k or o does nothing indeed.)

**"Not sure"**: I would add "skip": "Not sure, skip". The word "skip" explain next action if I'm not sure. I'm not afraid of selecting "Not sure, skip" because I understand it does nothing, it just skip the product.

**Comment by ArnaudBarre** [comment]
I agree to add "skip".

Yes letters are for keyboard actions (for desktop usage). It still working on my mac. Did you try on phone ?

**Comment by CharlesNepote** [comment]
"Skip" is definitely better, thanks. Keyboard actions seem to work now (maybe I misuse the app the previous times).
