### ISSUE TITLE
CORS-issue

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-hungergames-react#27]
Access to XMLHttpRequest at 'https://robotoff.openfoodfacts.org/api/v1/insights/annotate' from origin 'https://world.openfoodfacts.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ArnaudBarre** [comment]
I think robotoff should had a header Access-Control-Allow-Origin: *.openfoodfacts.org

**Comment by teolemon** [comment]
closing and reopening at robotoff. Yup. Filed on the wrong end. Closing and reopening on the RobotOFF repo
