### ISSUE TITLE
No questions left UI should present the selection controls

### ISSUE THREAD

**Issue by CloCkWeRX** [openfoodfacts/openfoodfacts-hungergames-react#31]
Reproduce steps:
 * Filter by a specific criteria - Country: Australia, Categories
 * Wait for the UI to load

![image](https://user-images.githubusercontent.com/365751/60567383-04f96d80-9da9-11e9-90a1-878c08b1f03f.png)

Expected:
 * I can easily navigate back or widen my search criteria

Actual:
 * I have to reload the whole UI, which does not retain my previous selections.

**Comment by alexfauquette** [comment]
Hi, yes it's a problem I met a few weeks ago. This PR should fix it ;)

https://github.com/openfoodfacts/openfoodfacts-hungergames/pull/35
