### ISSUE TITLE
Hunger games keeps requesting robotoff when the are no questions available

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-hungergames-react#7]
Ex: https://fr.openfoodfacts.org/hunger-game?brands=coraya
status=`no_questions` is returned, Hunger games keeps sending request to robotoff and the "loading..." prompt doesn't disappear.

**Comment by ArnaudBarre** [comment]
Ok sorry I was expected that the array is always return. I could check the status but an if it's simple for you you can return `{ status=no_questions, questions: [] }`

**Comment by raphael0202** [comment]
Even if the array is always returned, the issues remains.
